set_property SRC_FILE_INFO {cfile:{C:/Users/169050/Desktop/VHDL/Aula 5/FlipFlipD/FlipFlipD.srcs/constrs_1/imports/VHDL/Arty-A7-35-Master.xdc} rfile:../../../FlipFlipD.srcs/constrs_1/imports/VHDL/Arty-A7-35-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A8    IOSTANDARD LVCMOS33 } [get_ports { D }]; #IO_L12N_T1_MRCC_16 Sch=sw[0]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { Q }]; #IO_L24N_T3_35 Sch=led[4]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { clock }]; #IO_L11P_T1_SRCC_16 Sch=btn[1]
