set_property SRC_FILE_INFO {cfile:{C:/Users/169050/Desktop/VHDL/Aula 1/Circuito_1/Circuito_1.srcs/constrs_1/imports/VHDL/Arty-A7-35-Master.xdc} rfile:../../../Circuito_1.srcs/constrs_1/imports/VHDL/Arty-A7-35-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { S }]; #IO_L24N_T3_35 Sch=led[4]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L6N_T0_VREF_16 Sch=btn[0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { B }]; #IO_L11P_T1_SRCC_16 Sch=btn[1]
